package com.sogou.bizdev.compass.sample.mybatis.masterslave.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sogou.bizdev.compass.sample.common.po.AccountForTest;
import com.sogou.bizdev.compass.sample.common.po.AccountForTestExample;

public interface MybatisAccountDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPC.ACCOUNT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    int countByExample(AccountForTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPC.ACCOUNT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    int deleteByExample(AccountForTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPC.ACCOUNT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    int deleteByPrimaryKey(Long iAccountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPC.ACCOUNT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    int insert(AccountForTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPC.ACCOUNT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    int insertSelective(AccountForTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPC.ACCOUNT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    List<AccountForTest> selectByExample(AccountForTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPC.ACCOUNT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    AccountForTest selectByPrimaryKey(Long iAccountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPC.ACCOUNT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    int updateByExampleSelective(@Param("record") AccountForTest record, @Param("example") AccountForTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPC.ACCOUNT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    int updateByExample(@Param("record") AccountForTest record, @Param("example") AccountForTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPC.ACCOUNT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    int updateByPrimaryKeySelective(AccountForTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPC.ACCOUNT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    int updateByPrimaryKey(AccountForTest record);
}