package com.sogou.bizdev.compass.sample.common.po;

import java.math.BigDecimal;
import java.util.Date;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.I_ACCOUNT_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Long iAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.I_SOHU_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Long iSohuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_EMAIL
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_PASSWORD
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.D_REGIST_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Date dRegistDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.D_LOGIN_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Date dLoginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_ACTIVECODE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cActivecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.I_AGENT_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Long iAgentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_AGENT_NAME
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cAgentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.I_DISCOUNT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short iDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.B_TRUST
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short bTrust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_STATUS
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_PRIVILEGE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cPrivilege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.I_GROUP_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Long iGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_COMPANY_NAME
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cCompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_WEB
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cWeb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_INTRO
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_INDUSTRY
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_CONTACTOR
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cContactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_PROVINCE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_ZIP
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_ADDRESS
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_PHONE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_FAX
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cFax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.B_INVEST
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short bInvest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.B_AGENT_MANAGE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short bAgentManage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.VCHRMAINTENANCE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String vchrmaintenance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.VCHRSIGNED
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String vchrsigned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.VCHRSIGNED_NAME
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String vchrsignedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.B_IMPORTANT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short bImportant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_EXPIRE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cExpire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_TYPE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.D_MEMBER_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Date dMemberDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.D_END_MEMBER_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Date dEndMemberDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.B_EMAIL
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short bEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.B_VIP
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short bVip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_OPERATOR
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.B_PROTECT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short bProtect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_PRODUCT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cProduct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.I_MANAGE_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Long iManageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.B_MANAGE_CLIENT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short bManageClient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.B_REGION_AGENT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short bRegionAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_GRADE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_IDENTITY
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.B_ADMIN_PROTECT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short bAdminProtect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.I_MANAGE_TYPE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short iManageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.I_DISCOUNT_SEARCH
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short iDiscountSearch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.STATUS_REASON
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String statusReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.STATUS_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Date statusDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.ADMIN_REGION
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String adminRegion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.CHECK_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Date checkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.ISALLOW
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short isallow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.CAN_ADD_AGENT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short canAddAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.FIRST_INVEST
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Long firstInvest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.AGENT_ISDELETE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Long agentIsdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.ISSMOOTH
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short issmooth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.ISRESULT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short isresult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.ISBALANCE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short isbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.SECOND_AGENT_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Long secondAgentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.NEED_DVMM
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private BigDecimal needDvmm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.DVMM_OPEN_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Date dvmmOpenDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.ADMIN_OPEN_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Date adminOpenDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_PRODUCT2
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cProduct2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.ISMEMOIRE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short ismemoire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.MEMORANDUM
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String memorandum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.CPCADURL
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cpcadurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.MEMO
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.CLASSIFY
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Short classify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.CLASSIFY2
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Integer classify2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_WEBPHONE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cWebphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.C_ICP
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private String cIcp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPC.ACCOUNT.UC_UPDATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    private Long ucUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.I_ACCOUNT_ID
     *
     * @return the value of CPC.ACCOUNT.I_ACCOUNT_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Long getiAccountId() {
        return iAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.I_ACCOUNT_ID
     *
     * @param iAccountId the value for CPC.ACCOUNT.I_ACCOUNT_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setiAccountId(Long iAccountId) {
        this.iAccountId = iAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.I_SOHU_ID
     *
     * @return the value of CPC.ACCOUNT.I_SOHU_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Long getiSohuId() {
        return iSohuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.I_SOHU_ID
     *
     * @param iSohuId the value for CPC.ACCOUNT.I_SOHU_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setiSohuId(Long iSohuId) {
        this.iSohuId = iSohuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_EMAIL
     *
     * @return the value of CPC.ACCOUNT.C_EMAIL
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcEmail() {
        return cEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_EMAIL
     *
     * @param cEmail the value for CPC.ACCOUNT.C_EMAIL
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcEmail(String cEmail) {
        this.cEmail = cEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_PASSWORD
     *
     * @return the value of CPC.ACCOUNT.C_PASSWORD
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcPassword() {
        return cPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_PASSWORD
     *
     * @param cPassword the value for CPC.ACCOUNT.C_PASSWORD
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcPassword(String cPassword) {
        this.cPassword = cPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.D_REGIST_DATE
     *
     * @return the value of CPC.ACCOUNT.D_REGIST_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Date getdRegistDate() {
        return dRegistDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.D_REGIST_DATE
     *
     * @param dRegistDate the value for CPC.ACCOUNT.D_REGIST_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setdRegistDate(Date dRegistDate) {
        this.dRegistDate = dRegistDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.D_LOGIN_DATE
     *
     * @return the value of CPC.ACCOUNT.D_LOGIN_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Date getdLoginDate() {
        return dLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.D_LOGIN_DATE
     *
     * @param dLoginDate the value for CPC.ACCOUNT.D_LOGIN_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setdLoginDate(Date dLoginDate) {
        this.dLoginDate = dLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_ACTIVECODE
     *
     * @return the value of CPC.ACCOUNT.C_ACTIVECODE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcActivecode() {
        return cActivecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_ACTIVECODE
     *
     * @param cActivecode the value for CPC.ACCOUNT.C_ACTIVECODE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcActivecode(String cActivecode) {
        this.cActivecode = cActivecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.I_AGENT_ID
     *
     * @return the value of CPC.ACCOUNT.I_AGENT_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Long getiAgentId() {
        return iAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.I_AGENT_ID
     *
     * @param iAgentId the value for CPC.ACCOUNT.I_AGENT_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setiAgentId(Long iAgentId) {
        this.iAgentId = iAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_AGENT_NAME
     *
     * @return the value of CPC.ACCOUNT.C_AGENT_NAME
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcAgentName() {
        return cAgentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_AGENT_NAME
     *
     * @param cAgentName the value for CPC.ACCOUNT.C_AGENT_NAME
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcAgentName(String cAgentName) {
        this.cAgentName = cAgentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.I_DISCOUNT
     *
     * @return the value of CPC.ACCOUNT.I_DISCOUNT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getiDiscount() {
        return iDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.I_DISCOUNT
     *
     * @param iDiscount the value for CPC.ACCOUNT.I_DISCOUNT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setiDiscount(Short iDiscount) {
        this.iDiscount = iDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.B_TRUST
     *
     * @return the value of CPC.ACCOUNT.B_TRUST
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getbTrust() {
        return bTrust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.B_TRUST
     *
     * @param bTrust the value for CPC.ACCOUNT.B_TRUST
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setbTrust(Short bTrust) {
        this.bTrust = bTrust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_STATUS
     *
     * @return the value of CPC.ACCOUNT.C_STATUS
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcStatus() {
        return cStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_STATUS
     *
     * @param cStatus the value for CPC.ACCOUNT.C_STATUS
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcStatus(String cStatus) {
        this.cStatus = cStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_PRIVILEGE
     *
     * @return the value of CPC.ACCOUNT.C_PRIVILEGE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcPrivilege() {
        return cPrivilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_PRIVILEGE
     *
     * @param cPrivilege the value for CPC.ACCOUNT.C_PRIVILEGE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcPrivilege(String cPrivilege) {
        this.cPrivilege = cPrivilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.I_GROUP_ID
     *
     * @return the value of CPC.ACCOUNT.I_GROUP_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Long getiGroupId() {
        return iGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.I_GROUP_ID
     *
     * @param iGroupId the value for CPC.ACCOUNT.I_GROUP_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setiGroupId(Long iGroupId) {
        this.iGroupId = iGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_COMPANY_NAME
     *
     * @return the value of CPC.ACCOUNT.C_COMPANY_NAME
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcCompanyName() {
        return cCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_COMPANY_NAME
     *
     * @param cCompanyName the value for CPC.ACCOUNT.C_COMPANY_NAME
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcCompanyName(String cCompanyName) {
        this.cCompanyName = cCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_WEB
     *
     * @return the value of CPC.ACCOUNT.C_WEB
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcWeb() {
        return cWeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_WEB
     *
     * @param cWeb the value for CPC.ACCOUNT.C_WEB
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcWeb(String cWeb) {
        this.cWeb = cWeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_INTRO
     *
     * @return the value of CPC.ACCOUNT.C_INTRO
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcIntro() {
        return cIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_INTRO
     *
     * @param cIntro the value for CPC.ACCOUNT.C_INTRO
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcIntro(String cIntro) {
        this.cIntro = cIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_INDUSTRY
     *
     * @return the value of CPC.ACCOUNT.C_INDUSTRY
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcIndustry() {
        return cIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_INDUSTRY
     *
     * @param cIndustry the value for CPC.ACCOUNT.C_INDUSTRY
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcIndustry(String cIndustry) {
        this.cIndustry = cIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_CONTACTOR
     *
     * @return the value of CPC.ACCOUNT.C_CONTACTOR
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcContactor() {
        return cContactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_CONTACTOR
     *
     * @param cContactor the value for CPC.ACCOUNT.C_CONTACTOR
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcContactor(String cContactor) {
        this.cContactor = cContactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_PROVINCE
     *
     * @return the value of CPC.ACCOUNT.C_PROVINCE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcProvince() {
        return cProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_PROVINCE
     *
     * @param cProvince the value for CPC.ACCOUNT.C_PROVINCE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcProvince(String cProvince) {
        this.cProvince = cProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_ZIP
     *
     * @return the value of CPC.ACCOUNT.C_ZIP
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcZip() {
        return cZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_ZIP
     *
     * @param cZip the value for CPC.ACCOUNT.C_ZIP
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcZip(String cZip) {
        this.cZip = cZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_ADDRESS
     *
     * @return the value of CPC.ACCOUNT.C_ADDRESS
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcAddress() {
        return cAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_ADDRESS
     *
     * @param cAddress the value for CPC.ACCOUNT.C_ADDRESS
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcAddress(String cAddress) {
        this.cAddress = cAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_PHONE
     *
     * @return the value of CPC.ACCOUNT.C_PHONE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcPhone() {
        return cPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_PHONE
     *
     * @param cPhone the value for CPC.ACCOUNT.C_PHONE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcPhone(String cPhone) {
        this.cPhone = cPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_FAX
     *
     * @return the value of CPC.ACCOUNT.C_FAX
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcFax() {
        return cFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_FAX
     *
     * @param cFax the value for CPC.ACCOUNT.C_FAX
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcFax(String cFax) {
        this.cFax = cFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.B_INVEST
     *
     * @return the value of CPC.ACCOUNT.B_INVEST
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getbInvest() {
        return bInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.B_INVEST
     *
     * @param bInvest the value for CPC.ACCOUNT.B_INVEST
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setbInvest(Short bInvest) {
        this.bInvest = bInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.B_AGENT_MANAGE
     *
     * @return the value of CPC.ACCOUNT.B_AGENT_MANAGE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getbAgentManage() {
        return bAgentManage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.B_AGENT_MANAGE
     *
     * @param bAgentManage the value for CPC.ACCOUNT.B_AGENT_MANAGE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setbAgentManage(Short bAgentManage) {
        this.bAgentManage = bAgentManage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.VCHRMAINTENANCE
     *
     * @return the value of CPC.ACCOUNT.VCHRMAINTENANCE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getVchrmaintenance() {
        return vchrmaintenance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.VCHRMAINTENANCE
     *
     * @param vchrmaintenance the value for CPC.ACCOUNT.VCHRMAINTENANCE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setVchrmaintenance(String vchrmaintenance) {
        this.vchrmaintenance = vchrmaintenance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.VCHRSIGNED
     *
     * @return the value of CPC.ACCOUNT.VCHRSIGNED
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getVchrsigned() {
        return vchrsigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.VCHRSIGNED
     *
     * @param vchrsigned the value for CPC.ACCOUNT.VCHRSIGNED
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setVchrsigned(String vchrsigned) {
        this.vchrsigned = vchrsigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.VCHRSIGNED_NAME
     *
     * @return the value of CPC.ACCOUNT.VCHRSIGNED_NAME
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getVchrsignedName() {
        return vchrsignedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.VCHRSIGNED_NAME
     *
     * @param vchrsignedName the value for CPC.ACCOUNT.VCHRSIGNED_NAME
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setVchrsignedName(String vchrsignedName) {
        this.vchrsignedName = vchrsignedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.B_IMPORTANT
     *
     * @return the value of CPC.ACCOUNT.B_IMPORTANT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getbImportant() {
        return bImportant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.B_IMPORTANT
     *
     * @param bImportant the value for CPC.ACCOUNT.B_IMPORTANT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setbImportant(Short bImportant) {
        this.bImportant = bImportant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_EXPIRE
     *
     * @return the value of CPC.ACCOUNT.C_EXPIRE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcExpire() {
        return cExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_EXPIRE
     *
     * @param cExpire the value for CPC.ACCOUNT.C_EXPIRE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcExpire(String cExpire) {
        this.cExpire = cExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_TYPE
     *
     * @return the value of CPC.ACCOUNT.C_TYPE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcType() {
        return cType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_TYPE
     *
     * @param cType the value for CPC.ACCOUNT.C_TYPE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcType(String cType) {
        this.cType = cType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.D_MEMBER_DATE
     *
     * @return the value of CPC.ACCOUNT.D_MEMBER_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Date getdMemberDate() {
        return dMemberDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.D_MEMBER_DATE
     *
     * @param dMemberDate the value for CPC.ACCOUNT.D_MEMBER_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setdMemberDate(Date dMemberDate) {
        this.dMemberDate = dMemberDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.D_END_MEMBER_DATE
     *
     * @return the value of CPC.ACCOUNT.D_END_MEMBER_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Date getdEndMemberDate() {
        return dEndMemberDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.D_END_MEMBER_DATE
     *
     * @param dEndMemberDate the value for CPC.ACCOUNT.D_END_MEMBER_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setdEndMemberDate(Date dEndMemberDate) {
        this.dEndMemberDate = dEndMemberDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.B_EMAIL
     *
     * @return the value of CPC.ACCOUNT.B_EMAIL
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getbEmail() {
        return bEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.B_EMAIL
     *
     * @param bEmail the value for CPC.ACCOUNT.B_EMAIL
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setbEmail(Short bEmail) {
        this.bEmail = bEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.B_VIP
     *
     * @return the value of CPC.ACCOUNT.B_VIP
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getbVip() {
        return bVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.B_VIP
     *
     * @param bVip the value for CPC.ACCOUNT.B_VIP
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setbVip(Short bVip) {
        this.bVip = bVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_OPERATOR
     *
     * @return the value of CPC.ACCOUNT.C_OPERATOR
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcOperator() {
        return cOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_OPERATOR
     *
     * @param cOperator the value for CPC.ACCOUNT.C_OPERATOR
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcOperator(String cOperator) {
        this.cOperator = cOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.B_PROTECT
     *
     * @return the value of CPC.ACCOUNT.B_PROTECT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getbProtect() {
        return bProtect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.B_PROTECT
     *
     * @param bProtect the value for CPC.ACCOUNT.B_PROTECT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setbProtect(Short bProtect) {
        this.bProtect = bProtect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_PRODUCT
     *
     * @return the value of CPC.ACCOUNT.C_PRODUCT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcProduct() {
        return cProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_PRODUCT
     *
     * @param cProduct the value for CPC.ACCOUNT.C_PRODUCT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcProduct(String cProduct) {
        this.cProduct = cProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.I_MANAGE_ID
     *
     * @return the value of CPC.ACCOUNT.I_MANAGE_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Long getiManageId() {
        return iManageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.I_MANAGE_ID
     *
     * @param iManageId the value for CPC.ACCOUNT.I_MANAGE_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setiManageId(Long iManageId) {
        this.iManageId = iManageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.B_MANAGE_CLIENT
     *
     * @return the value of CPC.ACCOUNT.B_MANAGE_CLIENT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getbManageClient() {
        return bManageClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.B_MANAGE_CLIENT
     *
     * @param bManageClient the value for CPC.ACCOUNT.B_MANAGE_CLIENT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setbManageClient(Short bManageClient) {
        this.bManageClient = bManageClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.B_REGION_AGENT
     *
     * @return the value of CPC.ACCOUNT.B_REGION_AGENT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getbRegionAgent() {
        return bRegionAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.B_REGION_AGENT
     *
     * @param bRegionAgent the value for CPC.ACCOUNT.B_REGION_AGENT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setbRegionAgent(Short bRegionAgent) {
        this.bRegionAgent = bRegionAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_GRADE
     *
     * @return the value of CPC.ACCOUNT.C_GRADE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcGrade() {
        return cGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_GRADE
     *
     * @param cGrade the value for CPC.ACCOUNT.C_GRADE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcGrade(String cGrade) {
        this.cGrade = cGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_IDENTITY
     *
     * @return the value of CPC.ACCOUNT.C_IDENTITY
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcIdentity() {
        return cIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_IDENTITY
     *
     * @param cIdentity the value for CPC.ACCOUNT.C_IDENTITY
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcIdentity(String cIdentity) {
        this.cIdentity = cIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.B_ADMIN_PROTECT
     *
     * @return the value of CPC.ACCOUNT.B_ADMIN_PROTECT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getbAdminProtect() {
        return bAdminProtect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.B_ADMIN_PROTECT
     *
     * @param bAdminProtect the value for CPC.ACCOUNT.B_ADMIN_PROTECT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setbAdminProtect(Short bAdminProtect) {
        this.bAdminProtect = bAdminProtect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.I_MANAGE_TYPE
     *
     * @return the value of CPC.ACCOUNT.I_MANAGE_TYPE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getiManageType() {
        return iManageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.I_MANAGE_TYPE
     *
     * @param iManageType the value for CPC.ACCOUNT.I_MANAGE_TYPE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setiManageType(Short iManageType) {
        this.iManageType = iManageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.I_DISCOUNT_SEARCH
     *
     * @return the value of CPC.ACCOUNT.I_DISCOUNT_SEARCH
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getiDiscountSearch() {
        return iDiscountSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.I_DISCOUNT_SEARCH
     *
     * @param iDiscountSearch the value for CPC.ACCOUNT.I_DISCOUNT_SEARCH
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setiDiscountSearch(Short iDiscountSearch) {
        this.iDiscountSearch = iDiscountSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.STATUS_REASON
     *
     * @return the value of CPC.ACCOUNT.STATUS_REASON
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getStatusReason() {
        return statusReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.STATUS_REASON
     *
     * @param statusReason the value for CPC.ACCOUNT.STATUS_REASON
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setStatusReason(String statusReason) {
        this.statusReason = statusReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.STATUS_DATE
     *
     * @return the value of CPC.ACCOUNT.STATUS_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Date getStatusDate() {
        return statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.STATUS_DATE
     *
     * @param statusDate the value for CPC.ACCOUNT.STATUS_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.ADMIN_REGION
     *
     * @return the value of CPC.ACCOUNT.ADMIN_REGION
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getAdminRegion() {
        return adminRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.ADMIN_REGION
     *
     * @param adminRegion the value for CPC.ACCOUNT.ADMIN_REGION
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setAdminRegion(String adminRegion) {
        this.adminRegion = adminRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.CHECK_DATE
     *
     * @return the value of CPC.ACCOUNT.CHECK_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.CHECK_DATE
     *
     * @param checkDate the value for CPC.ACCOUNT.CHECK_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.ISALLOW
     *
     * @return the value of CPC.ACCOUNT.ISALLOW
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getIsallow() {
        return isallow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.ISALLOW
     *
     * @param isallow the value for CPC.ACCOUNT.ISALLOW
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setIsallow(Short isallow) {
        this.isallow = isallow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.CAN_ADD_AGENT
     *
     * @return the value of CPC.ACCOUNT.CAN_ADD_AGENT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getCanAddAgent() {
        return canAddAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.CAN_ADD_AGENT
     *
     * @param canAddAgent the value for CPC.ACCOUNT.CAN_ADD_AGENT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setCanAddAgent(Short canAddAgent) {
        this.canAddAgent = canAddAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.FIRST_INVEST
     *
     * @return the value of CPC.ACCOUNT.FIRST_INVEST
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Long getFirstInvest() {
        return firstInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.FIRST_INVEST
     *
     * @param firstInvest the value for CPC.ACCOUNT.FIRST_INVEST
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setFirstInvest(Long firstInvest) {
        this.firstInvest = firstInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.AGENT_ISDELETE
     *
     * @return the value of CPC.ACCOUNT.AGENT_ISDELETE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Long getAgentIsdelete() {
        return agentIsdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.AGENT_ISDELETE
     *
     * @param agentIsdelete the value for CPC.ACCOUNT.AGENT_ISDELETE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setAgentIsdelete(Long agentIsdelete) {
        this.agentIsdelete = agentIsdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.ISSMOOTH
     *
     * @return the value of CPC.ACCOUNT.ISSMOOTH
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getIssmooth() {
        return issmooth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.ISSMOOTH
     *
     * @param issmooth the value for CPC.ACCOUNT.ISSMOOTH
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setIssmooth(Short issmooth) {
        this.issmooth = issmooth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.ISRESULT
     *
     * @return the value of CPC.ACCOUNT.ISRESULT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getIsresult() {
        return isresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.ISRESULT
     *
     * @param isresult the value for CPC.ACCOUNT.ISRESULT
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setIsresult(Short isresult) {
        this.isresult = isresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.ISBALANCE
     *
     * @return the value of CPC.ACCOUNT.ISBALANCE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getIsbalance() {
        return isbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.ISBALANCE
     *
     * @param isbalance the value for CPC.ACCOUNT.ISBALANCE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setIsbalance(Short isbalance) {
        this.isbalance = isbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.SECOND_AGENT_ID
     *
     * @return the value of CPC.ACCOUNT.SECOND_AGENT_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Long getSecondAgentId() {
        return secondAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.SECOND_AGENT_ID
     *
     * @param secondAgentId the value for CPC.ACCOUNT.SECOND_AGENT_ID
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setSecondAgentId(Long secondAgentId) {
        this.secondAgentId = secondAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.NEED_DVMM
     *
     * @return the value of CPC.ACCOUNT.NEED_DVMM
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public BigDecimal getNeedDvmm() {
        return needDvmm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.NEED_DVMM
     *
     * @param needDvmm the value for CPC.ACCOUNT.NEED_DVMM
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setNeedDvmm(BigDecimal needDvmm) {
        this.needDvmm = needDvmm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.DVMM_OPEN_DATE
     *
     * @return the value of CPC.ACCOUNT.DVMM_OPEN_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Date getDvmmOpenDate() {
        return dvmmOpenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.DVMM_OPEN_DATE
     *
     * @param dvmmOpenDate the value for CPC.ACCOUNT.DVMM_OPEN_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setDvmmOpenDate(Date dvmmOpenDate) {
        this.dvmmOpenDate = dvmmOpenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.ADMIN_OPEN_DATE
     *
     * @return the value of CPC.ACCOUNT.ADMIN_OPEN_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Date getAdminOpenDate() {
        return adminOpenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.ADMIN_OPEN_DATE
     *
     * @param adminOpenDate the value for CPC.ACCOUNT.ADMIN_OPEN_DATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setAdminOpenDate(Date adminOpenDate) {
        this.adminOpenDate = adminOpenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_PRODUCT2
     *
     * @return the value of CPC.ACCOUNT.C_PRODUCT2
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcProduct2() {
        return cProduct2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_PRODUCT2
     *
     * @param cProduct2 the value for CPC.ACCOUNT.C_PRODUCT2
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcProduct2(String cProduct2) {
        this.cProduct2 = cProduct2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.ISMEMOIRE
     *
     * @return the value of CPC.ACCOUNT.ISMEMOIRE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getIsmemoire() {
        return ismemoire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.ISMEMOIRE
     *
     * @param ismemoire the value for CPC.ACCOUNT.ISMEMOIRE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setIsmemoire(Short ismemoire) {
        this.ismemoire = ismemoire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.MEMORANDUM
     *
     * @return the value of CPC.ACCOUNT.MEMORANDUM
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getMemorandum() {
        return memorandum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.MEMORANDUM
     *
     * @param memorandum the value for CPC.ACCOUNT.MEMORANDUM
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setMemorandum(String memorandum) {
        this.memorandum = memorandum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.CPCADURL
     *
     * @return the value of CPC.ACCOUNT.CPCADURL
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getCpcadurl() {
        return cpcadurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.CPCADURL
     *
     * @param cpcadurl the value for CPC.ACCOUNT.CPCADURL
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setCpcadurl(String cpcadurl) {
        this.cpcadurl = cpcadurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.MEMO
     *
     * @return the value of CPC.ACCOUNT.MEMO
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.MEMO
     *
     * @param memo the value for CPC.ACCOUNT.MEMO
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.CLASSIFY
     *
     * @return the value of CPC.ACCOUNT.CLASSIFY
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Short getClassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.CLASSIFY
     *
     * @param classify the value for CPC.ACCOUNT.CLASSIFY
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setClassify(Short classify) {
        this.classify = classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.CLASSIFY2
     *
     * @return the value of CPC.ACCOUNT.CLASSIFY2
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Integer getClassify2() {
        return classify2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.CLASSIFY2
     *
     * @param classify2 the value for CPC.ACCOUNT.CLASSIFY2
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setClassify2(Integer classify2) {
        this.classify2 = classify2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_WEBPHONE
     *
     * @return the value of CPC.ACCOUNT.C_WEBPHONE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcWebphone() {
        return cWebphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_WEBPHONE
     *
     * @param cWebphone the value for CPC.ACCOUNT.C_WEBPHONE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcWebphone(String cWebphone) {
        this.cWebphone = cWebphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.C_ICP
     *
     * @return the value of CPC.ACCOUNT.C_ICP
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public String getcIcp() {
        return cIcp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.C_ICP
     *
     * @param cIcp the value for CPC.ACCOUNT.C_ICP
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setcIcp(String cIcp) {
        this.cIcp = cIcp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPC.ACCOUNT.UC_UPDATE
     *
     * @return the value of CPC.ACCOUNT.UC_UPDATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public Long getUcUpdate() {
        return ucUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPC.ACCOUNT.UC_UPDATE
     *
     * @param ucUpdate the value for CPC.ACCOUNT.UC_UPDATE
     *
     * @mbggenerated Mon May 12 17:56:53 GMT+08:00 2014
     */
    public void setUcUpdate(Long ucUpdate) {
        this.ucUpdate = ucUpdate;
    }

	@Override
	public String toString() {
		return "Account [iAccountId=" + iAccountId + ", iSohuId=" + iSohuId
				+ ", cEmail=" + cEmail + ", cPassword=" + cPassword
				+ ", dRegistDate=" + dRegistDate + ", dLoginDate=" + dLoginDate
				+ ", cActivecode=" + cActivecode + ", iAgentId=" + iAgentId
				+ ", cAgentName=" + cAgentName + ", iDiscount=" + iDiscount
				+ ", bTrust=" + bTrust + ", cStatus=" + cStatus
				+ ", cPrivilege=" + cPrivilege + ", iGroupId=" + iGroupId
				+ ", cCompanyName=" + cCompanyName + ", cWeb=" + cWeb
				+ ", cIntro=" + cIntro + ", cIndustry=" + cIndustry
				+ ", cContactor=" + cContactor + ", cProvince=" + cProvince
				+ ", cZip=" + cZip + ", cAddress=" + cAddress + ", cPhone="
				+ cPhone + ", cFax=" + cFax + ", bInvest=" + bInvest
				+ ", bAgentManage=" + bAgentManage + ", vchrmaintenance="
				+ vchrmaintenance + ", vchrsigned=" + vchrsigned
				+ ", vchrsignedName=" + vchrsignedName + ", bImportant="
				+ bImportant + ", cExpire=" + cExpire + ", cType=" + cType
				+ ", dMemberDate=" + dMemberDate + ", dEndMemberDate="
				+ dEndMemberDate + ", bEmail=" + bEmail + ", bVip=" + bVip
				+ ", cOperator=" + cOperator + ", bProtect=" + bProtect
				+ ", cProduct=" + cProduct + ", iManageId=" + iManageId
				+ ", bManageClient=" + bManageClient + ", bRegionAgent="
				+ bRegionAgent + ", cGrade=" + cGrade + ", cIdentity="
				+ cIdentity + ", bAdminProtect=" + bAdminProtect
				+ ", iManageType=" + iManageType + ", iDiscountSearch="
				+ iDiscountSearch + ", statusReason=" + statusReason
				+ ", statusDate=" + statusDate + ", adminRegion=" + adminRegion
				+ ", checkDate=" + checkDate + ", isallow=" + isallow
				+ ", canAddAgent=" + canAddAgent + ", firstInvest="
				+ firstInvest + ", agentIsdelete=" + agentIsdelete
				+ ", issmooth=" + issmooth + ", isresult=" + isresult
				+ ", isbalance=" + isbalance + ", secondAgentId="
				+ secondAgentId + ", needDvmm=" + needDvmm + ", dvmmOpenDate="
				+ dvmmOpenDate + ", adminOpenDate=" + adminOpenDate
				+ ", cProduct2=" + cProduct2 + ", ismemoire=" + ismemoire
				+ ", memorandum=" + memorandum + ", cpcadurl=" + cpcadurl
				+ ", memo=" + memo + ", classify=" + classify + ", classify2="
				+ classify2 + ", cWebphone=" + cWebphone + ", cIcp=" + cIcp
				+ ", ucUpdate=" + ucUpdate + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((adminOpenDate == null) ? 0 : adminOpenDate.hashCode());
		result = prime * result
				+ ((adminRegion == null) ? 0 : adminRegion.hashCode());
		result = prime * result
				+ ((agentIsdelete == null) ? 0 : agentIsdelete.hashCode());
		result = prime * result
				+ ((bAdminProtect == null) ? 0 : bAdminProtect.hashCode());
		result = prime * result
				+ ((bAgentManage == null) ? 0 : bAgentManage.hashCode());
		result = prime * result + ((bEmail == null) ? 0 : bEmail.hashCode());
		result = prime * result
				+ ((bImportant == null) ? 0 : bImportant.hashCode());
		result = prime * result + ((bInvest == null) ? 0 : bInvest.hashCode());
		result = prime * result
				+ ((bManageClient == null) ? 0 : bManageClient.hashCode());
		result = prime * result
				+ ((bProtect == null) ? 0 : bProtect.hashCode());
		result = prime * result
				+ ((bRegionAgent == null) ? 0 : bRegionAgent.hashCode());
		result = prime * result + ((bTrust == null) ? 0 : bTrust.hashCode());
		result = prime * result + ((bVip == null) ? 0 : bVip.hashCode());
		result = prime * result
				+ ((cActivecode == null) ? 0 : cActivecode.hashCode());
		result = prime * result
				+ ((cAddress == null) ? 0 : cAddress.hashCode());
		result = prime * result
				+ ((cAgentName == null) ? 0 : cAgentName.hashCode());
		result = prime * result
				+ ((cCompanyName == null) ? 0 : cCompanyName.hashCode());
		result = prime * result
				+ ((cContactor == null) ? 0 : cContactor.hashCode());
		result = prime * result + ((cEmail == null) ? 0 : cEmail.hashCode());
		result = prime * result + ((cExpire == null) ? 0 : cExpire.hashCode());
		result = prime * result + ((cFax == null) ? 0 : cFax.hashCode());
		result = prime * result + ((cGrade == null) ? 0 : cGrade.hashCode());
		result = prime * result + ((cIcp == null) ? 0 : cIcp.hashCode());
		result = prime * result
				+ ((cIdentity == null) ? 0 : cIdentity.hashCode());
		result = prime * result
				+ ((cIndustry == null) ? 0 : cIndustry.hashCode());
		result = prime * result + ((cIntro == null) ? 0 : cIntro.hashCode());
		result = prime * result
				+ ((cOperator == null) ? 0 : cOperator.hashCode());
		result = prime * result
				+ ((cPassword == null) ? 0 : cPassword.hashCode());
		result = prime * result + ((cPhone == null) ? 0 : cPhone.hashCode());
		result = prime * result
				+ ((cPrivilege == null) ? 0 : cPrivilege.hashCode());
		result = prime * result
				+ ((cProduct == null) ? 0 : cProduct.hashCode());
		result = prime * result
				+ ((cProduct2 == null) ? 0 : cProduct2.hashCode());
		result = prime * result
				+ ((cProvince == null) ? 0 : cProvince.hashCode());
		result = prime * result + ((cStatus == null) ? 0 : cStatus.hashCode());
		result = prime * result + ((cType == null) ? 0 : cType.hashCode());
		result = prime * result + ((cWeb == null) ? 0 : cWeb.hashCode());
		result = prime * result
				+ ((cWebphone == null) ? 0 : cWebphone.hashCode());
		result = prime * result + ((cZip == null) ? 0 : cZip.hashCode());
		result = prime * result
				+ ((canAddAgent == null) ? 0 : canAddAgent.hashCode());
		result = prime * result
				+ ((checkDate == null) ? 0 : checkDate.hashCode());
		result = prime * result
				+ ((classify == null) ? 0 : classify.hashCode());
		result = prime * result
				+ ((classify2 == null) ? 0 : classify2.hashCode());
		result = prime * result
				+ ((cpcadurl == null) ? 0 : cpcadurl.hashCode());
		result = prime * result
				+ ((dEndMemberDate == null) ? 0 : dEndMemberDate.hashCode());
		result = prime * result
				+ ((dLoginDate == null) ? 0 : dLoginDate.hashCode());
		result = prime * result
				+ ((dMemberDate == null) ? 0 : dMemberDate.hashCode());
		result = prime * result
				+ ((dRegistDate == null) ? 0 : dRegistDate.hashCode());
		result = prime * result
				+ ((dvmmOpenDate == null) ? 0 : dvmmOpenDate.hashCode());
		result = prime * result
				+ ((firstInvest == null) ? 0 : firstInvest.hashCode());
		result = prime * result
				+ ((iAccountId == null) ? 0 : iAccountId.hashCode());
		result = prime * result
				+ ((iAgentId == null) ? 0 : iAgentId.hashCode());
		result = prime * result
				+ ((iDiscount == null) ? 0 : iDiscount.hashCode());
		result = prime * result
				+ ((iDiscountSearch == null) ? 0 : iDiscountSearch.hashCode());
		result = prime * result
				+ ((iGroupId == null) ? 0 : iGroupId.hashCode());
		result = prime * result
				+ ((iManageId == null) ? 0 : iManageId.hashCode());
		result = prime * result
				+ ((iManageType == null) ? 0 : iManageType.hashCode());
		result = prime * result + ((iSohuId == null) ? 0 : iSohuId.hashCode());
		result = prime * result + ((isallow == null) ? 0 : isallow.hashCode());
		result = prime * result
				+ ((isbalance == null) ? 0 : isbalance.hashCode());
		result = prime * result
				+ ((ismemoire == null) ? 0 : ismemoire.hashCode());
		result = prime * result
				+ ((isresult == null) ? 0 : isresult.hashCode());
		result = prime * result
				+ ((issmooth == null) ? 0 : issmooth.hashCode());
		result = prime * result + ((memo == null) ? 0 : memo.hashCode());
		result = prime * result
				+ ((memorandum == null) ? 0 : memorandum.hashCode());
		result = prime * result
				+ ((needDvmm == null) ? 0 : needDvmm.hashCode());
		result = prime * result
				+ ((secondAgentId == null) ? 0 : secondAgentId.hashCode());
		result = prime * result
				+ ((statusDate == null) ? 0 : statusDate.hashCode());
		result = prime * result
				+ ((statusReason == null) ? 0 : statusReason.hashCode());
		result = prime * result
				+ ((ucUpdate == null) ? 0 : ucUpdate.hashCode());
		result = prime * result
				+ ((vchrmaintenance == null) ? 0 : vchrmaintenance.hashCode());
		result = prime * result
				+ ((vchrsigned == null) ? 0 : vchrsigned.hashCode());
		result = prime * result
				+ ((vchrsignedName == null) ? 0 : vchrsignedName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Account other = (Account) obj;
		if (adminOpenDate == null) {
			if (other.adminOpenDate != null)
				return false;
		} else if (!adminOpenDate.equals(other.adminOpenDate))
			return false;
		if (adminRegion == null) {
			if (other.adminRegion != null)
				return false;
		} else if (!adminRegion.equals(other.adminRegion))
			return false;
		if (agentIsdelete == null) {
			if (other.agentIsdelete != null)
				return false;
		} else if (!agentIsdelete.equals(other.agentIsdelete))
			return false;
		if (bAdminProtect == null) {
			if (other.bAdminProtect != null)
				return false;
		} else if (!bAdminProtect.equals(other.bAdminProtect))
			return false;
		if (bAgentManage == null) {
			if (other.bAgentManage != null)
				return false;
		} else if (!bAgentManage.equals(other.bAgentManage))
			return false;
		if (bEmail == null) {
			if (other.bEmail != null)
				return false;
		} else if (!bEmail.equals(other.bEmail))
			return false;
		if (bImportant == null) {
			if (other.bImportant != null)
				return false;
		} else if (!bImportant.equals(other.bImportant))
			return false;
		if (bInvest == null) {
			if (other.bInvest != null)
				return false;
		} else if (!bInvest.equals(other.bInvest))
			return false;
		if (bManageClient == null) {
			if (other.bManageClient != null)
				return false;
		} else if (!bManageClient.equals(other.bManageClient))
			return false;
		if (bProtect == null) {
			if (other.bProtect != null)
				return false;
		} else if (!bProtect.equals(other.bProtect))
			return false;
		if (bRegionAgent == null) {
			if (other.bRegionAgent != null)
				return false;
		} else if (!bRegionAgent.equals(other.bRegionAgent))
			return false;
		if (bTrust == null) {
			if (other.bTrust != null)
				return false;
		} else if (!bTrust.equals(other.bTrust))
			return false;
		if (bVip == null) {
			if (other.bVip != null)
				return false;
		} else if (!bVip.equals(other.bVip))
			return false;
		if (cActivecode == null) {
			if (other.cActivecode != null)
				return false;
		} else if (!cActivecode.equals(other.cActivecode))
			return false;
		if (cAddress == null) {
			if (other.cAddress != null)
				return false;
		} else if (!cAddress.equals(other.cAddress))
			return false;
		if (cAgentName == null) {
			if (other.cAgentName != null)
				return false;
		} else if (!cAgentName.equals(other.cAgentName))
			return false;
		if (cCompanyName == null) {
			if (other.cCompanyName != null)
				return false;
		} else if (!cCompanyName.equals(other.cCompanyName))
			return false;
		if (cContactor == null) {
			if (other.cContactor != null)
				return false;
		} else if (!cContactor.equals(other.cContactor))
			return false;
		if (cEmail == null) {
			if (other.cEmail != null)
				return false;
		} else if (!cEmail.equals(other.cEmail))
			return false;
		if (cExpire == null) {
			if (other.cExpire != null)
				return false;
		} else if (!cExpire.equals(other.cExpire))
			return false;
		if (cFax == null) {
			if (other.cFax != null)
				return false;
		} else if (!cFax.equals(other.cFax))
			return false;
		if (cGrade == null) {
			if (other.cGrade != null)
				return false;
		} else if (!cGrade.equals(other.cGrade))
			return false;
		if (cIcp == null) {
			if (other.cIcp != null)
				return false;
		} else if (!cIcp.equals(other.cIcp))
			return false;
		if (cIdentity == null) {
			if (other.cIdentity != null)
				return false;
		} else if (!cIdentity.equals(other.cIdentity))
			return false;
		if (cIndustry == null) {
			if (other.cIndustry != null)
				return false;
		} else if (!cIndustry.equals(other.cIndustry))
			return false;
		if (cIntro == null) {
			if (other.cIntro != null)
				return false;
		} else if (!cIntro.equals(other.cIntro))
			return false;
		if (cOperator == null) {
			if (other.cOperator != null)
				return false;
		} else if (!cOperator.equals(other.cOperator))
			return false;
		if (cPassword == null) {
			if (other.cPassword != null)
				return false;
		} else if (!cPassword.equals(other.cPassword))
			return false;
		if (cPhone == null) {
			if (other.cPhone != null)
				return false;
		} else if (!cPhone.equals(other.cPhone))
			return false;
		if (cPrivilege == null) {
			if (other.cPrivilege != null)
				return false;
		} else if (!cPrivilege.equals(other.cPrivilege))
			return false;
		if (cProduct == null) {
			if (other.cProduct != null)
				return false;
		} else if (!cProduct.equals(other.cProduct))
			return false;
		if (cProduct2 == null) {
			if (other.cProduct2 != null)
				return false;
		} else if (!cProduct2.equals(other.cProduct2))
			return false;
		if (cProvince == null) {
			if (other.cProvince != null)
				return false;
		} else if (!cProvince.equals(other.cProvince))
			return false;
		if (cStatus == null) {
			if (other.cStatus != null)
				return false;
		} else if (!cStatus.equals(other.cStatus))
			return false;
		if (cType == null) {
			if (other.cType != null)
				return false;
		} else if (!cType.equals(other.cType))
			return false;
		if (cWeb == null) {
			if (other.cWeb != null)
				return false;
		} else if (!cWeb.equals(other.cWeb))
			return false;
		if (cWebphone == null) {
			if (other.cWebphone != null)
				return false;
		} else if (!cWebphone.equals(other.cWebphone))
			return false;
		if (cZip == null) {
			if (other.cZip != null)
				return false;
		} else if (!cZip.equals(other.cZip))
			return false;
		if (canAddAgent == null) {
			if (other.canAddAgent != null)
				return false;
		} else if (!canAddAgent.equals(other.canAddAgent))
			return false;
		if (checkDate == null) {
			if (other.checkDate != null)
				return false;
		} else if (!checkDate.equals(other.checkDate))
			return false;
		if (classify == null) {
			if (other.classify != null)
				return false;
		} else if (!classify.equals(other.classify))
			return false;
		if (classify2 == null) {
			if (other.classify2 != null)
				return false;
		} else if (!classify2.equals(other.classify2))
			return false;
		if (cpcadurl == null) {
			if (other.cpcadurl != null)
				return false;
		} else if (!cpcadurl.equals(other.cpcadurl))
			return false;
		if (dEndMemberDate == null) {
			if (other.dEndMemberDate != null)
				return false;
		} else if (!dEndMemberDate.equals(other.dEndMemberDate))
			return false;
		if (dLoginDate == null) {
			if (other.dLoginDate != null)
				return false;
		} else if (!dLoginDate.equals(other.dLoginDate))
			return false;
		if (dMemberDate == null) {
			if (other.dMemberDate != null)
				return false;
		} else if (!dMemberDate.equals(other.dMemberDate))
			return false;
		if (dRegistDate == null) {
			if (other.dRegistDate != null)
				return false;
		} else if (!dRegistDate.equals(other.dRegistDate))
			return false;
		if (dvmmOpenDate == null) {
			if (other.dvmmOpenDate != null)
				return false;
		} else if (!dvmmOpenDate.equals(other.dvmmOpenDate))
			return false;
		if (firstInvest == null) {
			if (other.firstInvest != null)
				return false;
		} else if (!firstInvest.equals(other.firstInvest))
			return false;
		if (iAccountId == null) {
			if (other.iAccountId != null)
				return false;
		} else if (!iAccountId.equals(other.iAccountId))
			return false;
		if (iAgentId == null) {
			if (other.iAgentId != null)
				return false;
		} else if (!iAgentId.equals(other.iAgentId))
			return false;
		if (iDiscount == null) {
			if (other.iDiscount != null)
				return false;
		} else if (!iDiscount.equals(other.iDiscount))
			return false;
		if (iDiscountSearch == null) {
			if (other.iDiscountSearch != null)
				return false;
		} else if (!iDiscountSearch.equals(other.iDiscountSearch))
			return false;
		if (iGroupId == null) {
			if (other.iGroupId != null)
				return false;
		} else if (!iGroupId.equals(other.iGroupId))
			return false;
		if (iManageId == null) {
			if (other.iManageId != null)
				return false;
		} else if (!iManageId.equals(other.iManageId))
			return false;
		if (iManageType == null) {
			if (other.iManageType != null)
				return false;
		} else if (!iManageType.equals(other.iManageType))
			return false;
		if (iSohuId == null) {
			if (other.iSohuId != null)
				return false;
		} else if (!iSohuId.equals(other.iSohuId))
			return false;
		if (isallow == null) {
			if (other.isallow != null)
				return false;
		} else if (!isallow.equals(other.isallow))
			return false;
		if (isbalance == null) {
			if (other.isbalance != null)
				return false;
		} else if (!isbalance.equals(other.isbalance))
			return false;
		if (ismemoire == null) {
			if (other.ismemoire != null)
				return false;
		} else if (!ismemoire.equals(other.ismemoire))
			return false;
		if (isresult == null) {
			if (other.isresult != null)
				return false;
		} else if (!isresult.equals(other.isresult))
			return false;
		if (issmooth == null) {
			if (other.issmooth != null)
				return false;
		} else if (!issmooth.equals(other.issmooth))
			return false;
		if (memo == null) {
			if (other.memo != null)
				return false;
		} else if (!memo.equals(other.memo))
			return false;
		if (memorandum == null) {
			if (other.memorandum != null)
				return false;
		} else if (!memorandum.equals(other.memorandum))
			return false;
		if (needDvmm == null) {
			if (other.needDvmm != null)
				return false;
		} else if (!needDvmm.equals(other.needDvmm))
			return false;
		if (secondAgentId == null) {
			if (other.secondAgentId != null)
				return false;
		} else if (!secondAgentId.equals(other.secondAgentId))
			return false;
		if (statusDate == null) {
			if (other.statusDate != null)
				return false;
		} else if (!statusDate.equals(other.statusDate))
			return false;
		if (statusReason == null) {
			if (other.statusReason != null)
				return false;
		} else if (!statusReason.equals(other.statusReason))
			return false;
		if (ucUpdate == null) {
			if (other.ucUpdate != null)
				return false;
		} else if (!ucUpdate.equals(other.ucUpdate))
			return false;
		if (vchrmaintenance == null) {
			if (other.vchrmaintenance != null)
				return false;
		} else if (!vchrmaintenance.equals(other.vchrmaintenance))
			return false;
		if (vchrsigned == null) {
			if (other.vchrsigned != null)
				return false;
		} else if (!vchrsigned.equals(other.vchrsigned))
			return false;
		if (vchrsignedName == null) {
			if (other.vchrsignedName != null)
				return false;
		} else if (!vchrsignedName.equals(other.vchrsignedName))
			return false;
		return true;
	}
    
    
}