package com.sogou.bizdev.compass.sample.common.po;

import java.util.Date;

public class Plan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpcplan_0101.cpcplanid
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    private Long cpcplanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpcplan_0101.name
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpcplan_0101.ispause
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    private Integer ispause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpcplan_0101.accountid
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    private Long accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpcplan_0101.createdate
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpcplan_0101.chgdate
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    private Date chgdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpcplan_0101.start_date
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpcplan_0101.end_date
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpcplan_0101.cpcplanid
     *
     * @return the value of cpcplan_0101.cpcplanid
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    public Long getCpcplanid() {
        return cpcplanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpcplan_0101.cpcplanid
     *
     * @param cpcplanid the value for cpcplan_0101.cpcplanid
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    public void setCpcplanid(Long cpcplanid) {
        this.cpcplanid = cpcplanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpcplan_0101.name
     *
     * @return the value of cpcplan_0101.name
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpcplan_0101.name
     *
     * @param name the value for cpcplan_0101.name
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpcplan_0101.ispause
     *
     * @return the value of cpcplan_0101.ispause
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    public Integer getIspause() {
        return ispause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpcplan_0101.ispause
     *
     * @param ispause the value for cpcplan_0101.ispause
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    public void setIspause(Integer ispause) {
        this.ispause = ispause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpcplan_0101.accountid
     *
     * @return the value of cpcplan_0101.accountid
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    public Long getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpcplan_0101.accountid
     *
     * @param accountid the value for cpcplan_0101.accountid
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    public void setAccountid(Long accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpcplan_0101.createdate
     *
     * @return the value of cpcplan_0101.createdate
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpcplan_0101.createdate
     *
     * @param createdate the value for cpcplan_0101.createdate
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpcplan_0101.chgdate
     *
     * @return the value of cpcplan_0101.chgdate
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    public Date getChgdate() {
        return chgdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpcplan_0101.chgdate
     *
     * @param chgdate the value for cpcplan_0101.chgdate
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    public void setChgdate(Date chgdate) {
        this.chgdate = chgdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpcplan_0101.start_date
     *
     * @return the value of cpcplan_0101.start_date
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpcplan_0101.start_date
     *
     * @param startDate the value for cpcplan_0101.start_date
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpcplan_0101.end_date
     *
     * @return the value of cpcplan_0101.end_date
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpcplan_0101.end_date
     *
     * @param endDate the value for cpcplan_0101.end_date
     *
     * @mbggenerated Mon May 12 17:27:03 GMT+08:00 2014
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

	@Override
	public String toString() {
		return "Plan [cpcplanid=" + cpcplanid + ", name=" + name + ", ispause="
				+ ispause + ", accountid=" + accountid + ", createdate="
				+ createdate + ", chgdate=" + chgdate + ", startDate="
				+ startDate + ", endDate=" + endDate + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((accountid == null) ? 0 : accountid.hashCode());
		result = prime * result + ((chgdate == null) ? 0 : chgdate.hashCode());
		result = prime * result
				+ ((cpcplanid == null) ? 0 : cpcplanid.hashCode());
		result = prime * result
				+ ((createdate == null) ? 0 : createdate.hashCode());
		result = prime * result + ((endDate == null) ? 0 : endDate.hashCode());
		result = prime * result + ((ispause == null) ? 0 : ispause.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result
				+ ((startDate == null) ? 0 : startDate.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Plan other = (Plan) obj;
		if (accountid == null) {
			if (other.accountid != null)
				return false;
		} else if (!accountid.equals(other.accountid))
			return false;
		if (chgdate == null) {
			if (other.chgdate != null)
				return false;
		} else if (!chgdate.equals(other.chgdate))
			return false;
		if (cpcplanid == null) {
			if (other.cpcplanid != null)
				return false;
		} else if (!cpcplanid.equals(other.cpcplanid))
			return false;
		if (createdate == null) {
			if (other.createdate != null)
				return false;
		} else if (!createdate.equals(other.createdate))
			return false;
		if (endDate == null) {
			if (other.endDate != null)
				return false;
		} else if (!endDate.equals(other.endDate))
			return false;
		if (ispause == null) {
			if (other.ispause != null)
				return false;
		} else if (!ispause.equals(other.ispause))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (startDate == null) {
			if (other.startDate != null)
				return false;
		} else if (!startDate.equals(other.startDate))
			return false;
		return true;
	}
    
    
}